name: PMPlus
main: cc.wanforme.nukkit.PMPlus.PluginManagerPlus
version: "2.0.1"
# nukkit API 版本号居然更新了，funny
api: ["2.0.0"]

# 启动时加载
load: STARTUP

author: wanne
description: 基于 nukkit 插件管理器的增强
# to do github address
website: 

# 软依赖，加载时非必要
softdepend: []
# 依赖，加载时必要
depend: []
# 自定义前缀，暂时没发现有什么用
#prefix: PM
# 加载前需要加载哪些插件
loadbefore: []


commands: 
  pm: 
    description: PM 主命令
    usage: "/pm load|unload [{plugin1},{plugin2}...]"
#    aliases: ["PM"] # 2.0别名不再支持大写字母
    permission: PMPlus.command.pm
    permission-message: "您没有权限执行 /pm 命令！"
    
permissions: 
  PMPlus.command.pm: 
    description: "pm主命令权限"
    default: op
#   children:
#     PMPlus.command.pm.test:
#       description: "Use the test feature in the example command"
#       default: true